# -*- coding: utf-8 -*-
"""Wavelet2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oCt7w8ZsBy_k7ZftRjdWts2iJN1-Fim1
"""

!pip install PyWavelets

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import pywt

df = pd.read_csv("samples.csv")
df.head(10)

signal1 = df.iloc[:, 0].values
signal2 = df.iloc[:, 1].values
signal3 = df.iloc[:, 2].values
signal4 = df.iloc[:, 3].values
signal5 = df.iloc[:, 4].values
signal6 = df.iloc[:, 5].values
signal7 = df.iloc[:, 6].values
signal8 = df.iloc[:, 7].values
signal9 = df.iloc[:, 8].values
signal10 = df.iloc[:, 9].values
signal11 = df.iloc[:, 10].values
signal12 = df.iloc[:, 11].values
signal13 = df.iloc[:, 12].values
signal14 = df.iloc[:, 13].values
signal15 = df.iloc[:, 14].values
signal16 = df.iloc[:, 15].values
signal17 = df.iloc[:, 16].values
signal18 = df.iloc[:, 17].values
signal19 = df.iloc[:, 18].values
signal20 = df.iloc[:, 19].values
signal21 = df.iloc[:, 20].values
signal22 = df.iloc[:, 21].values
signal23 = df.iloc[:, 22].values
signal24 = df.iloc[:, 23].values

t1 = np.linspace(0, 10, len(signal1))
t2 = np.linspace(0, 10, len(signal2))
t3 = np.linspace(0, 10, len(signal3))
t4 = np.linspace(0, 10, len(signal4))
t5 = np.linspace(0, 10, len(signal5))
t6 = np.linspace(0, 10, len(signal6))
t7 = np.linspace(0, 10, len(signal7))
t8 = np.linspace(0, 10, len(signal8))
t9 = np.linspace(0, 10, len(signal9))
t10 = np.linspace(0, 10, len(signal10))
t11 = np.linspace(0, 10, len(signal11))
t12 = np.linspace(0, 10, len(signal12))
t13 = np.linspace(0, 10, len(signal13))
t14 = np.linspace(0, 10, len(signal14))
t15 = np.linspace(0, 10, len(signal15))
t16 = np.linspace(0, 10, len(signal16))
t17 = np.linspace(0, 10, len(signal17))
t18 = np.linspace(0, 10, len(signal18))
t19 = np.linspace(0, 10, len(signal19))
t20 = np.linspace(0, 10, len(signal20))
t21 = np.linspace(0, 10, len(signal21))
t22 = np.linspace(0, 10, len(signal22))
t23 = np.linspace(0, 10, len(signal23))
t24 = np.linspace(0, 10, len(signal24))

scales = np.arange(1, 190)
wavelet = 'cmor'

coeffs1, freqs1 = pywt.cwt(signal1, scales, wavelet)
coeffs2, freqs2 = pywt.cwt(signal2, scales, wavelet)
coeffs3, freqs3 = pywt.cwt(signal3, scales, wavelet)
coeffs4, freqs4 = pywt.cwt(signal4, scales, wavelet)
coeffs5, freqs5 = pywt.cwt(signal5, scales, wavelet)
coeffs6, freqs6 = pywt.cwt(signal6, scales, wavelet)
coeffs7, freqs7 = pywt.cwt(signal7, scales, wavelet)
coeffs8, freqs8 = pywt.cwt(signal8, scales, wavelet)
coeffs9, freqs9 = pywt.cwt(signal9, scales, wavelet)
coeffs10, freqs10 = pywt.cwt(signal10, scales, wavelet)
coeffs11, freqs11 = pywt.cwt(signal11, scales, wavelet)
coeffs12, freqs12 = pywt.cwt(signal12, scales, wavelet)

coeffs13, freqs13 = pywt.cwt(signal13, scales, wavelet)
coeffs14, freqs14 = pywt.cwt(signal14, scales, wavelet)
coeffs15, freqs15 = pywt.cwt(signal5, scales, wavelet)
coeffs16, freqs16 = pywt.cwt(signal16, scales, wavelet)
coeffs17, freqs17 = pywt.cwt(signal17, scales, wavelet)
coeffs18, freqs18 = pywt.cwt(signal18, scales, wavelet)
coeffs19, freqs19 = pywt.cwt(signal19, scales, wavelet)
coeffs20, freqs20 = pywt.cwt(signal20, scales, wavelet)
coeffs21, freqs21 = pywt.cwt(signal21, scales, wavelet)
coeffs22, freqs22 = pywt.cwt(signal22, scales, wavelet)
coeffs23, freqs23 = pywt.cwt(signal23, scales, wavelet)
coeffs24, freqs24 = pywt.cwt(signal24, scales, wavelet)

plt.style.use('grayscale')
plt.figure(figsize=(18, 8))
plt.subplot(2, 1, 1)
plt.plot(t1, signal1, "k", label = "I (Persona 1)")
plt.title('"I (Persona 1)"')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.grid = (True)

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs1), aspect='auto', extent=[t1[0], t1[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) para I (Persona 1)')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t1, scales)

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(24, 12))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs1), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs1), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.1)

ax.contour(t, s, np.abs(coeffs1), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=2.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Escala')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para I')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t2, signal2, "k")
plt.title('Persona 1. II')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs2), aspect='auto', extent=[t2[0], t2[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) para II')
plt.xlabel('Tiempo')
plt.ylabel('Escala')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t2, scales)

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs2), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs2), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs2), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para II')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t3, signal3, "k")
plt.title('Persona 1. III')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')



plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs3), aspect='auto', extent=[t3[0], t3[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT)')
plt.xlabel('Tiempo')
plt.ylabel('Escala')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t3, scales)

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs3), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs3), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs3), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Escala')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para III')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t4, signal4, "k")
plt.title('Persona 1. AVR')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs4), aspect='auto', extent=[t4[0], t4[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) para AVR')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t4, scales)

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(40, 20))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs4), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs4), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs4), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=3.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Escala')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t5, signal5, "k")
plt.title('Persona 1. AVL')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.grid = (True)

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs5), aspect='auto', extent=[t5[0], t5[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de AVL')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t5, scales)

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs5), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs5), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs5), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Escala')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para AVL')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t6, signal6, "k")
plt.title('Persona 1. AVF')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs6), aspect='auto', extent=[t6[0], t6[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de AVF')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t6, scales)

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs6), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs6), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs6), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para AVF')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t7, signal7, "k")
plt.title('Persona 1. V1')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs7), aspect='auto', extent=[t7[0], t7[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V1')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t7, scales)
plt.style.use('grayscale')

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs7), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs7), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs7), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para V1')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t8, signal8, "k")
plt.title('Persona 1. V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs8), aspect='auto', extent=[t8[0], t8[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t8, scales)
plt.style.use('grayscale')

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs8), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs8), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs8), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para V2')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t9, signal9, "k")
plt.title('V3')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs9), aspect='auto', extent=[t9[0], t9[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V3')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t9, scales)
plt.style.use('grayscale')

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs9), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs9), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs9), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para V3')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t10, signal10, "k")
plt.title('Persona 1. V4')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs10), aspect='auto', extent=[t10[0], t10[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V4')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t10, scales)
plt.style.use('grayscale')

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(30, 15))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs10), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs10), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs10), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para V4')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t11, signal11, "k")
plt.title('Persona 1. V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs11), aspect='auto', extent=[t11[0], t11[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t11, scales)
plt.style.use('grayscale')

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(28, 14))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs11), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs11), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs11), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para V5')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t12, signal12, "k")
plt.title('V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs12), aspect='auto', extent=[t12[0], t12[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

# Crear una malla 3D
t, s = np.meshgrid(t12, scales)
plt.style.use('grayscale')

# Graficar el escalograma en 3D
fig = plt.figure(figsize=(28, 14))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(t, s, np.abs(coeffs12), cmap='jet')

surf = ax.plot_surface(t, s, np.abs(coeffs12), cmap='jet', alpha=0.7, rstride=1, cstride=1, edgecolors='k', linewidth=0.2)

ax.contour(t, s, np.abs(coeffs12), zdir='z', offset=0, cmap='jet', linestyles='solid', linewidths=5.5)

# Etiquetas y título
ax.set_xlabel('Tiempo')
ax.set_ylabel('Frecuencia')
ax.set_zlabel('Magnitud de Coeficientes')
ax.set_title('Escalograma en 3D para V6')

# Mejorar la perspectiva
ax.view_init(elev=45, azim=225)

# Barra de color
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, label='Amplitud')

plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t13, signal13, "k")
plt.title('Persona 2. II')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs13), aspect='auto', extent=[t13[0], t13[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de II')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t17, signal17, "k")
plt.title('Persona 3. II')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs17), aspect='auto', extent=[t17[0], t17[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de II')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t21, signal21, "k")
plt.title('Persona 4. II')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs21), aspect='auto', extent=[t21[0], t21[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de II')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t14, signal14, "k")
plt.title('Persona 2. V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs14), aspect='auto', extent=[t14[0], t14[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t18, signal18, "k")
plt.title('Persona 3. V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs18), aspect='auto', extent=[t18[0], t18[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')


plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t22, signal22, "k")
plt.title('Persona 4. V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs22), aspect='auto', extent=[t22[0], t22[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V2')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t15, signal15, "k")
plt.title('Persona 2. V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs15), aspect='auto', extent=[t15[0], t15[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t19, signal19, "k")
plt.title('Persona 3. V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs19), aspect='auto', extent=[t19[0], t19[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t23, signal23, "k")
plt.title('Persona 4. V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs23), aspect='auto', extent=[t23[0], t23[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V5')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t16, signal16, "k")
plt.title('Persona 2. V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs16), aspect='auto', extent=[t16[0], t16[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t20, signal20, "k")
plt.title('Persona 3. V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs20), aspect='auto', extent=[t20[0], t20[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

plt.style.use('grayscale')
plt.figure(figsize=(10, 6))
plt.subplot(2, 1, 1)
plt.plot(t24, signal24, "k")
plt.title('Persona 4. V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')

plt.subplot(2, 1, 2)
plt.imshow(np.abs(coeffs24), aspect='auto', extent=[t24[0], t24[-1], scales[-1], scales[0]], cmap='jet')
plt.title('Transformada Wavelet Continua (CWT) de V6')
plt.xlabel('Tiempo')
plt.ylabel('Frecuencia')
plt.colorbar(label='Amplitud')

plt.tight_layout()
plt.show()

plt.style.use('Solarize_Light2')
plt.figure(figsize=(14, 7))

plt.subplot(12, 1, 1, label = "I")
plt.plot(t1, signal1, "k")

plt.subplot(12, 1, 2)
plt.plot(t2, signal2, "k")

plt.subplot(12, 1, 3)
plt.plot(t3, signal3, "k")

plt.subplot(12, 1, 4)
plt.plot(t4, signal4, "k")

plt.subplot(12, 1, 5)
plt.plot(t5, signal5, "k")

plt.subplot(12, 1, 6)
plt.plot(t6, signal6, "k")

plt.subplot(12, 1, 7)
plt.plot(t7, signal7, "k")

plt.subplot(12, 1, 8)
plt.plot(t8, signal8, "k")

plt.subplot(12, 1, 9)
plt.plot(t9, signal9, "k")

plt.subplot(12, 1, 10)
plt.plot(t10, signal10, "k")

plt.subplot(12, 1, 11)
plt.plot(t11, signal11, "k")

plt.subplot(12, 1, 6)
plt.plot(t12, signal12, "k")